/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module alu_adder_22 (
    input [15:0] a,
    input [15:0] b,
    input [0:0] alufn,
    output reg [15:0] out,
    output reg z,
    output reg v,
    output reg n
  );
  
  
  
  reg [15:0] s;
  
  always @* begin
    
    case (alufn)
      default: begin
        s = 16'h0000;
      end
      1'h0: begin
        s = a + b;
      end
      1'h1: begin
        s = a - b;
      end
    endcase
    n = s[15+0-:1];
    v = (a[15+0-:1] & (b[15+0-:1] ^ alufn) & ~s[15+0-:1]) | (~a[15+0-:1] & ~(b[15+0-:1] ^ alufn) & s[15+0-:1]);
    z = ~(|s);
    out = s;
  end
endmodule
