/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module alu_mux_12 (
    input [5:0] alufn,
    input asel,
    input [3:0] bsel,
    input [1:0] wdsel,
    input [15:0] ra_data,
    input [15:0] rb_data,
    output reg [15:0] out
  );
  
  
  
  wire [16-1:0] M_asel_mux_comp_out;
  reg [16-1:0] M_asel_mux_comp_ra_data;
  reg [1-1:0] M_asel_mux_comp_asel;
  asel_mux_17 asel_mux_comp (
    .ra_data(M_asel_mux_comp_ra_data),
    .asel(M_asel_mux_comp_asel),
    .out(M_asel_mux_comp_out)
  );
  
  wire [16-1:0] M_bsel_mux_comp_out;
  reg [16-1:0] M_bsel_mux_comp_rb_data;
  reg [4-1:0] M_bsel_mux_comp_bsel;
  bsel_mux_18 bsel_mux_comp (
    .rb_data(M_bsel_mux_comp_rb_data),
    .bsel(M_bsel_mux_comp_bsel),
    .out(M_bsel_mux_comp_out)
  );
  
  wire [16-1:0] M_alu_comp_out;
  wire [1-1:0] M_alu_comp_z;
  wire [1-1:0] M_alu_comp_v;
  wire [1-1:0] M_alu_comp_n;
  reg [16-1:0] M_alu_comp_a;
  reg [16-1:0] M_alu_comp_b;
  reg [6-1:0] M_alu_comp_alufn;
  alu_19 alu_comp (
    .a(M_alu_comp_a),
    .b(M_alu_comp_b),
    .alufn(M_alu_comp_alufn),
    .out(M_alu_comp_out),
    .z(M_alu_comp_z),
    .v(M_alu_comp_v),
    .n(M_alu_comp_n)
  );
  
  wire [16-1:0] M_wdsel_comp_out;
  reg [16-1:0] M_wdsel_comp_alu;
  reg [2-1:0] M_wdsel_comp_wdsel;
  wdsel_mux_20 wdsel_comp (
    .alu(M_wdsel_comp_alu),
    .wdsel(M_wdsel_comp_wdsel),
    .out(M_wdsel_comp_out)
  );
  
  always @* begin
    out = 1'h0;
    M_asel_mux_comp_asel = asel;
    M_asel_mux_comp_ra_data = ra_data;
    M_bsel_mux_comp_bsel = bsel;
    M_bsel_mux_comp_rb_data = rb_data;
    M_alu_comp_a = M_asel_mux_comp_out;
    M_alu_comp_b = M_bsel_mux_comp_out;
    M_alu_comp_alufn = alufn;
    M_wdsel_comp_wdsel = wdsel;
    M_wdsel_comp_alu = M_alu_comp_out;
    out = M_wdsel_comp_out;
  end
endmodule
