/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module asel_mux_17 (
    input [15:0] ra_data,
    input asel,
    output reg [15:0] out
  );
  
  
  
  reg [15:0] asel_1;
  
  always @* begin
    out = 16'h0000;
    asel_1 = 9'h000;
    
    case (asel)
      1'h0: begin
        out = ra_data;
      end
      1'h1: begin
        out = asel_1;
      end
    endcase
  end
endmodule
