/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module au_top_0 (
    input clk,
    input rst_n,
    input [10:0] io_dip,
    output reg [11:0] led_light,
    output reg [7:0] io_seg,
    output reg [2:0] io_sel,
    input usb_rx,
    output reg usb_tx
  );
  
  
  
  reg rst;
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_1 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  wire [3-1:0] M_init_io_sel;
  wire [8-1:0] M_init_io_seg;
  wire [12-1:0] M_init_led_lights;
  wire [1-1:0] M_init_usb_tx;
  reg [11-1:0] M_init_io_dip;
  reg [1-1:0] M_init_usb_rx;
  initialise_2 init (
    .clk(clk),
    .rst(rst),
    .io_dip(M_init_io_dip),
    .usb_rx(M_init_usb_rx),
    .io_sel(M_init_io_sel),
    .io_seg(M_init_io_seg),
    .led_lights(M_init_led_lights),
    .usb_tx(M_init_usb_tx)
  );
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    M_init_usb_rx = usb_rx;
    usb_tx = M_init_usb_tx;
    M_init_io_dip = io_dip;
    led_light = M_init_led_lights;
    io_seg = M_init_io_seg;
    io_sel = M_init_io_sel;
  end
endmodule
