/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module bsel_mux_18 (
    input [15:0] rb_data,
    input [3:0] bsel,
    output reg [15:0] out
  );
  
  
  
  reg [15:0] bsel_1;
  
  reg [15:0] bsel_2;
  
  reg [15:0] bsel_3;
  
  reg [15:0] bsel_4;
  
  reg [15:0] bsel_5;
  
  reg [15:0] bsel_6;
  
  reg [15:0] bsel_7;
  
  reg [15:0] bsel_8;
  
  reg [15:0] bsel_9;
  
  reg [15:0] bsel_A;
  
  always @* begin
    out = 1'h0;
    bsel_1 = 9'h00b;
    bsel_2 = 9'h015;
    bsel_3 = 9'h026;
    bsel_4 = 9'h051;
    bsel_5 = 9'h0ba;
    bsel_6 = 9'h134;
    bsel_7 = 9'h0c8;
    bsel_8 = 9'h1d0;
    bsel_9 = 9'h1a0;
    bsel_A = 9'h000;
    
    case (bsel)
      4'h0: begin
        out = rb_data;
      end
      4'h1: begin
        out = bsel_1;
      end
      4'h2: begin
        out = bsel_2;
      end
      4'h3: begin
        out = bsel_3;
      end
      4'h4: begin
        out = bsel_4;
      end
      4'h5: begin
        out = bsel_5;
      end
      4'h6: begin
        out = bsel_6;
      end
      4'h7: begin
        out = bsel_7;
      end
      4'h8: begin
        out = bsel_8;
      end
      4'h9: begin
        out = bsel_9;
      end
      4'ha: begin
        out = bsel_A;
      end
    endcase
  end
endmodule
