/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module buttonInput_5 (
    input clk,
    input rst,
    input [8:0] button,
    output reg bsel,
    output reg checkForInput
  );
  
  
  
  localparam IDLE_buttonInput = 4'd0;
  localparam B1_buttonInput = 4'd1;
  localparam B2_buttonInput = 4'd2;
  localparam B3_buttonInput = 4'd3;
  localparam B4_buttonInput = 4'd4;
  localparam B5_buttonInput = 4'd5;
  localparam B6_buttonInput = 4'd6;
  localparam B7_buttonInput = 4'd7;
  localparam B8_buttonInput = 4'd8;
  localparam B9_buttonInput = 4'd9;
  
  reg [3:0] M_buttonInput_d, M_buttonInput_q = IDLE_buttonInput;
  
  always @* begin
    M_buttonInput_d = M_buttonInput_q;
    
    bsel = 4'h0;
    checkForInput = 1'h0;
    
    case (M_buttonInput_q)
      IDLE_buttonInput: begin
        checkForInput = 1'h0;
        if (button[0+0-:1]) begin
          M_buttonInput_d = B1_buttonInput;
        end else begin
          if (button[1+0-:1]) begin
            M_buttonInput_d = B2_buttonInput;
          end else begin
            if (button[2+0-:1]) begin
              M_buttonInput_d = B3_buttonInput;
            end else begin
              if (button[3+0-:1]) begin
                M_buttonInput_d = B4_buttonInput;
              end else begin
                if (button[4+0-:1]) begin
                  M_buttonInput_d = B5_buttonInput;
                end else begin
                  if (button[5+0-:1]) begin
                    M_buttonInput_d = B6_buttonInput;
                  end else begin
                    if (button[6+0-:1]) begin
                      M_buttonInput_d = B7_buttonInput;
                    end else begin
                      if (button[7+0-:1]) begin
                        M_buttonInput_d = B8_buttonInput;
                      end else begin
                        if (button[8+0-:1]) begin
                          M_buttonInput_d = B9_buttonInput;
                        end else begin
                          M_buttonInput_d = IDLE_buttonInput;
                        end
                      end
                    end
                  end
                end
              end
            end
          end
        end
      end
      B1_buttonInput: begin
        bsel = 4'h1;
        checkForInput = 1'h1;
        M_buttonInput_d = IDLE_buttonInput;
      end
      B2_buttonInput: begin
        bsel = 4'h2;
        checkForInput = 1'h1;
        M_buttonInput_d = IDLE_buttonInput;
      end
      B3_buttonInput: begin
        bsel = 4'h3;
        checkForInput = 1'h1;
        M_buttonInput_d = IDLE_buttonInput;
      end
      B4_buttonInput: begin
        bsel = 4'h4;
        checkForInput = 1'h1;
        M_buttonInput_d = IDLE_buttonInput;
      end
      B5_buttonInput: begin
        bsel = 4'h5;
        checkForInput = 1'h1;
        M_buttonInput_d = IDLE_buttonInput;
      end
      B6_buttonInput: begin
        bsel = 4'h6;
        checkForInput = 1'h1;
        M_buttonInput_d = IDLE_buttonInput;
      end
      B7_buttonInput: begin
        bsel = 4'h7;
        checkForInput = 1'h1;
        M_buttonInput_d = IDLE_buttonInput;
      end
      B8_buttonInput: begin
        bsel = 4'h8;
        checkForInput = 1'h1;
        M_buttonInput_d = IDLE_buttonInput;
      end
      B9_buttonInput: begin
        bsel = 4'h9;
        checkForInput = 1'h1;
        M_buttonInput_d = IDLE_buttonInput;
      end
    endcase
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_buttonInput_q <= 1'h0;
    end else begin
      M_buttonInput_q <= M_buttonInput_d;
    end
  end
  
endmodule
