/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module wdsel_mux_20 (
    input [15:0] alu,
    input [1:0] wdsel,
    output reg [15:0] out
  );
  
  
  
  reg [15:0] k;
  
  always @* begin
    
    case (wdsel)
      default: begin
        k = 16'h0000;
      end
      2'h0: begin
        k = alu;
      end
      2'h1: begin
        k = 16'h0000;
      end
      2'h2: begin
        k = 16'hffff;
      end
    endcase
    out = k;
  end
endmodule
